version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: "/src-tauri"
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
