// AUTO-GENERATED - do not edit by hand.
// Generated by: python scripts/gen_types.py

export interface RpcErrorResponse {
  jsonrpc?: "2.0";
  id?: string | number | null;
  error: RpcError;
}

export interface RpcSuccessResponse {
  jsonrpc?: "2.0";
  id?: string | number | null;
  result: unknown;
}

export interface RpcError {
  code: number;
  message: string;
  data?: unknown;
}

export interface RpcRequest {
  jsonrpc?: "2.0";
  id?: string | number | null;
  method: string;
  params?: unknown;
}

export type RpcResponse = RpcSuccessResponse | RpcErrorResponse;

export interface RpcNotification {
  jsonrpc?: "2.0";
  method: string;
  params?: unknown;
}

export interface TaskProgress {
  task_id: string;
  progress: number;
  message?: string | null;
}

export interface TaskSnapshot {
  task_id: string;
  method: string;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  kind: "async" | "blocking";
  cancellable: boolean;
  cancel_requested?: boolean;
  progress?: number | null;
  message?: string | null;
  result?: unknown;
  error?: string | null;
}

export interface TaskCancelResult {
  task_id: string;
  cancelled: boolean;
  reason?: string | null;
}

export interface TaskCancelParams {
  task_id: string;
}

export interface TaskGetParams {
  task_id: string;
}

export interface TaskRemoveResult {
  task_id: string;
  removed: boolean;
  reason?: string | null;
}

export interface TaskIdResult {
  task_id: string;
}

export interface BackendReadyPayload {
  version: string;
  protocol_version: string;
  capabilities?: Array<string>;
}

export interface LogPayload {
  seq?: number | null;
  timestamp_ms?: number | null;
  level?: "debug" | "info" | "warning" | "error";
  stream?: "stderr" | "process";
  source?: string;
  message: string;
  context?: Record<string, unknown> | null;
}

export interface RpcMethodMap {
  "echo": { params: unknown; result: unknown };
  "task.list": { params: null; result: Array<TaskSnapshot> };
  "task.get": { params: TaskGetParams; result: TaskSnapshot | null };
  "task.remove": { params: TaskGetParams; result: TaskRemoveResult };
  "task.cancel": { params: TaskCancelParams; result: TaskCancelResult };
  "task.long": { params: null; result: TaskIdResult };
  "task.blocking": { params: null; result: TaskIdResult };
}

export type RpcMethod = keyof RpcMethodMap;
export type RpcParams<M extends RpcMethod> = RpcMethodMap[M]["params"];
export type RpcResult<M extends RpcMethod> = RpcMethodMap[M]["result"];
