// AUTO-GENERATED - do not edit by hand.
// Generated by: python scripts/gen_types.py

export interface RpcErrorResponse {
  jsonrpc?: "2.0";
  id?: string | null;
  error: RpcError;
}

export interface RpcSuccessResponse {
  jsonrpc?: "2.0";
  id?: string | null;
  result: unknown;
}

export interface RpcError {
  code: number;
  message: string;
  data?: unknown;
}

export interface RpcRequest {
  jsonrpc?: "2.0";
  id?: string | null;
  method: string;
  params?: unknown;
}

export type RpcResponse = RpcSuccessResponse | RpcErrorResponse;

export interface RpcNotification {
  jsonrpc?: "2.0";
  method: string;
  params?: unknown;
}

export interface TaskStatus {
  task_id: string;
  method: string;
  status: "pending" | "running" | "done" | "error" | "cancelled";
  kind?: "async" | "blocking" | null;
  cancellable?: boolean | null;
  cancel_requested?: boolean;
  progress?: number | null;
  message?: string | null;
}

export interface TaskResult {
  task_id: string;
  method: string;
  result?: unknown;
  error?: string | null;
}

export interface TaskProgress {
  task_id: string;
  progress: number;
  message?: string | null;
}

export interface TaskSummary {
  task_id: string;
  method: string;
  status: "pending" | "running" | "done" | "error" | "cancelled";
  kind: "async" | "blocking";
  cancellable: boolean;
  cancel_requested?: boolean;
}

export interface TaskCancelResult {
  task_id: string;
  cancelled: boolean;
  reason?: string | null;
}

export interface SidecarReadyPayload {
  version: string;
  capabilities?: Array<string>;
}

export interface LogPayload {
  level: "debug" | "info" | "warning" | "error";
  message: string;
  context?: Record<string, unknown> | null;
}
